[project]
name = "flask-app"
version = "0.1.0"
description = "A simple FastAPI app deployed via CI/CD"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "fastapi",
    "uvicorn",
    "boto3",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
